name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      adminToken:
        type: string
        required: true
      visibility:
        type: choice
        description: Filiera di appartenenza
        default: public
        options: 
        - internal
        - public
        - private
      filiera:
        type: choice
        description: Filiera di appartenenza
        options: 
        - corebanking
        - test
      repositoryName:
        type: string
        required: true        
        description: Nome del repository
        default: test-template1
      apiSpecName:
        type: string
        required: true              
        description: Nome file API Spec
        default: order-service
jobs:
  create_repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Create repository from template
        run: |
           chmod +x ./scripts/createRepositoryFromTemplate.sh
           ./scripts/createRepositoryFromTemplate.sh --$VISIBILITY $ORG $REPO $API_SPEC_NAME
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.adminToken }}
          ORG: ${{ github.event.inputs.filiera }}
          REPO: ${{ github.event.inputs.repositoryName }}
          API_SPEC_NAME: ${{ github.event.inputs.apiSpecName }}
          VISIBILITY: ${{ github.event.inputs.visibility }}
